### ISSUE TITLE
build failure unless build type is release

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/hyperscan#3]
Building for alpine linux I get this error (as build type has to be None for alpine)

```
/hyperscan-5.3.1/unit/internal/masked_move.cpp:35:10: fatal error: util/masked_move.h: No such file or directory
943   35 | #include "util/masked_move.h"
```
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/277952/raw

If I patch and add "NONE" to the types that sets RELEASE_BUILD 

```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -30,7 +30,7 @@
     message(STATUS "Build type ${CMAKE_BUILD_TYPE}")
 endif()

-if(CMAKE_BUILD_TYPE MATCHES RELEASE|RELWITHDEBINFO|MINSIZEREL)
+if(CMAKE_BUILD_TYPE MATCHES NONE|RELEASE|RELWITHDEBINFO|MINSIZEREL)
     message(STATUS "using release build")
     set(RELEASE_BUILD TRUE)
 else()
```

It compiles as it misses the problem files, but the tools are not compiled now.

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/277980

I would like to keep the tools, as there is already an hyperscan-tools package on alpine.

**Comment by markos** [comment]
is this on aarch64?

**Comment by a16bitsysop** [comment]
It is the same on aarch64 x86 and x86_64, I tried to patch masked_move.cpp so the include was util/x86/masked_move.h but it still couldn't find it.

**Comment by markos** [comment]
could you please paste the exact cmake invokation? I can't see it in the logs.

**Comment by a16bitsysop** [comment]
Here it is:
```
build() {
        local _march="-march=native"
        case "${CARCH:-native}" in
                x86|x86_64)
                        _march="-march=core2" ;;
        esac

        if [ "$CBUILD" != "$CHOST" ]; then
                CMAKE_CROSSOPTS="-DCMAKE_SYSTEM_NAME=Linux -DCMAKE_HOST_SYSTEM_NAME=Linux"
        fi
        cmake -B build \
                -DCMAKE_INSTALL_PREFIX=/usr \
                -DCMAKE_INSTALL_LIBDIR=lib \
                -DCMAKE_BUILD_TYPE=None \
                -DCMAKE_C_FLAGS="$CFLAGS $_march" \
                -DCMAKE_CXX_FLAGS="$CXXFLAGS $_march" \
                -DBUILD_STATIC_AND_SHARED=ON \
                "$CMAKE_CROSSOPTS" .
        cmake --build build --target all dev-reference
}
```

Looking at the log again it does actually build hscheck and hsbench, but not hsdump

```
[ 94%] Linking CXX shared library lib/libhs.so
475[ 94%] Linking CXX executable ../../bin/hscheck
476[ 94%] Built target hs_shared
477Scanning dependencies of target unit-hyperscan
478[ 94%] Built target hscheck
479[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/allocators.cpp.o
480[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/gtest/gtest-all.cc.o
481[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/arg_checks.cpp.o
482[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/behaviour.cpp.o
483[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/expr_info.cpp.o
484[ 95%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/bad_patterns.cpp.o
485[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/extparam.cpp.o
486[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/identical.cpp.o
487[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/literals.cpp.o
488[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/logical_combination.cpp.o
489[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/main.cpp.o
490[ 96%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/scratch_in_use.cpp.o
491[ 97%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/order.cpp.o
492[ 97%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/multi.cpp.o
493[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/single.cpp.o
494[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/scratch_op.cpp.o
495[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/serialize.cpp.o
496[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/som.cpp.o
497[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/stream_op.cpp.o
498[ 98%] Building CXX object unit/CMakeFiles/unit-hyperscan.dir/hyperscan/test_util.cpp.o
499[ 98%] Linking CXX executable ../../bin/hsbench
500[ 98%] Built target hsbench
501[ 98%] Linking CXX executable ../../bin/hscollider
502[ 98%] Built target hscollider
503[100%] Linking CXX executable ../bin/unit-hyperscan
504[100%] Built target unit-hyperscan
```

**Comment by markos** [comment]
so, internal unit tests -where the original build failure comes from- are not built at all when doing release builds, so changing the CMAKE_BUILD_TYPE should skip building those and avoid the build failure. However, that still doesn't fix the compiler error. I've fixed it so that it doesn't fail again, will commit in a second.
However, hsdump is only built when DUMP_SUPPORT is enabled. Beware however, that this enables extremely verbose debug output and significantly drops performance.

**Comment by markos** [comment]
Could you check the fix in the branch bugfix/fix-maskedmove-include ?

**Comment by a16bitsysop** [comment]
Ok thanks will try it.  Didn't know that about hsdump, also didn't notice hscollider.  So will drop hdump and add hscollider.

**Comment by a16bitsysop** [comment]
With just the header patch for testing (as the release patch would negate it).  It has passed on x86_64 and failed on x86 (aarch64 build is still waiting)

https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/278030/raw

**Comment by markos** [comment]
Ok, that's different, this is because some intrinsics are missing due to AVX/AVX2 are not available. It can be fixed easily but I wonder if it's worth keeping IA32 support. I don't have a ia32 environment available atm, I'll need to create one and test. But I think this should go in a different ticket.

**Comment by a16bitsysop** [comment]
Ok will open another ticket, it would be better to fix as upstream still support it.  It built on x86 from intel/hyperscan

**Comment by a16bitsysop** [comment]
Builds on aarch64 and x86_64 with release patch as well
