### ISSUE TITLE
build failure on x86

### ISSUE THREAD

**Issue by a16bitsysop** [VectorCamp/hyperscan#4]
Build fails for x86 when building on Alpine Linux, log here:
https://gitlab.alpinelinux.org/a16bitsysop/aports/-/jobs/278030/raw

```
407/builds/a16bitsysop/aports/community/hyperscan/src/hyperscan-5.3.1/src/util/arch/x86/simd_utils.h: In function 'movq':
408/builds/a16bitsysop/aports/community/hyperscan/src/hyperscan-5.3.1/src/util/arch/x86/simd_utils.h:128:12: error: implicit declaration of function '_mm_cvtsi128_si64'; did you mean '_mm_cvtsi128_si32'? [-Werror=implicit-function-declaration]
409  128 |     return _mm_cvtsi128_si64(in);
410      |            ^~~~~~~~~~~~~~~~~
411      |            _mm_cvtsi128_si32
```

**Comment by markos** [comment]
hi, @a16bitsysop, could you please check branch https://github.com/VectorCamp/hyperscan/tree/bugfix/fix-ia32-build? It should fix the x64/IA32 build failures -at least it does on my local Debian i386 environment.

**Comment by a16bitsysop** [comment]
Yes that fixes it for building as well
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/16306/pipelines

**Comment by a16bitsysop** [comment]
Trying a non release build now

**Comment by a16bitsysop** [comment]
Yes non release builds works as well thanks, are you going to tag a new release with these fixes?

**Comment by markos** [comment]
https://github.com/VectorCamp/hyperscan/releases/tag/v5.3.2

**Comment by a16bitsysop** [comment]
Thanks

**Comment by a16bitsysop** [comment]
The new tag doesn’t include the masked_move.cpp patch, but it’s not needed for release building.

It will be updated pretty soon on alpine Linux to 5.3.2, have enabled hyperscan for suricata on aarch64 and working on enabling it for rspamd on aarch64
